### ISSUE TITLE
No bookcovers generated

### ISSUE THREAD

**Issue by stormsh** [Yetangitu/owncloud-apps#11]
Hi there, since the update to oc 8.1.1 and therefore to opds 0.6.8 my ebookreader doesn't generate bookcovers after download anymore. Right in the feed are no book covers due to a bug in Aldiko (https://github.com/rvolz/BicBucStriim/issues/80). But Aldiko generated the covers just fine after the ebook was downloaded.
OPDS Catalog runs on an Ubuntu Server 14.04 with OC 8.1.1 and php 5.5.9.
The Ebookreader is latest Aldiko on Android 5.0.1. 
Before the OC and OPDS update this worked just fine. Didn't change anything else, just updated everything. So I assumed that I look here for the problem first.
Need any more information?
Thx 4 F1.
st.

**Comment by Yetangitu** [comment]
I assume you mean your client program does not generate any covers for downloaded books anymore? If this is the case, I'd look for a problem in that client program (or device). Assuming that the books themselves are readable? If not, that would point at a file corruption issue, either on the device or in Owncloud.

Do you see book covers in any other OPDS client?

Aldiko does not show any covers due to that bug you mention so I would not expect to see them there. Try FBreader on Android, this should - an in my case does - work as intended, covers and all. If you see covers in FBreader, the problem does not lie with the OPDS Catalog. If no covers show up and you are sure the publications on your account do have covers which can be generated by the Owncloud preview providers (of which OPDS Catalog contains one implementation - the ePub PP), AND those preview providers are enabled (check in OPDS Catalog admin settings and/or in the Owncloud config file, look for the 'enabledPreviewProviders' key)... I'd like to know more. However, I do suspect your problem lies elsewhere, based on the information provided and the fact that It Works For Me(R)...

**Comment by stormsh** [comment]
Thanks for your help. I appreciate it.

>I assume you mean your client program does not generate any covers for downloaded books anymore?

Yes, that is what I meant ;). The preview function is enabled in admin section (for epubs only) and in the config I found an array:

 >'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\MP3',
    2 => 'OC\\Preview\\TXT',
    3 => 'OC\\Preview\\MarkDown',
    11 => 'OC\\Preview\\Epub',
  ),

I think this is also correct. 

I tried Lucifox for Firefox and looked through nearly 500 bookpreviews. I found out, that some books show a cover (in the opds preview), some don't. The books that show the preview within the opds catalog have their covers generated correctly after download. The books that don't show the covers in the preview don't generate covers. Just a green placeholder (see image).
![cp](https://cloud.githubusercontent.com/assets/4153852/9424185/a7a9b51e-48e2-11e5-9e95-a365743374c4.jpg)
So because not all books are affected and all readers/opds catalog viewers (I tried Aldiko, FBReader and Lucifox) show the same behavior with the same books, it might be some kind of strange file corruption that only affects the covers. Never heard of something like that before. The texts in the books are readable. And I am 100% sure a lot of the books that don't show covers now, showed them before. Because I read a lot of them and can't remember a single book without cover until the update to oc 8.1.1 and opds 0.6.8.
So because I don't think this has to do with opds catalog or owncloud, you can happily close this issue. 
I think I have a look at the catalog files itself and try to generate the books/covers within calibre again, uploading them to oc again to see if that helps.

Thanks again. :+1:

st.

**Comment by Yetangitu** [comment]
Try to open one of the affected ePubs with zip or an ePub editor to see whether the ePub has a cover, whether it is readable and defined in the metadata. The ePub standard (as it is) does not define a cover so it did not take long for several competing 'standards' to try to fill that void, some more widespread (and supported) than others: https://www.google.se/search?q=epub+cover+standard
