### ISSUE TITLE
OPDS Library from NC 12 not seen on Android device

### ISSUE THREAD

**Issue by heviiguy** [Yetangitu/owncloud-apps#53]
I cannot access my (activated) OPDS library on my Android device with either FBReader or with Moon+Reader.
When trying with the former, I get: "failed to connect to host FooBar...". With the latter I get: "hostname in certificate didn't match..."
Yet I have no problems connecting to my NC using the same log-in with the same device.
I accept that the above might be a bit sparse in terms of useful details but, I've no idea about even trouble-shooting this issue. Could somebody please provide some suggestions?

**Comment by heviiguy** [comment]
More details:

- I initially tried to link my existing calibre library to /var/www/html/nextcloud/Library . When that resulted in the above, I copied the entire calibre library to this location (and changed permissions to Apache)

- Running my address opds address in OPDS-Validator results in a message of "Premature end of file"

**Comment by Yetangitu** [comment]
This problem is caused by your OPDS client app not supporting name-based virtual hosts, usually because it doesn't support SNI (http://www.ietf.org/rfc/rfc4366.txt). One of the solutions is to use a different OPDS client. If that is not an option you can run an extra site specifically for those clients on an alternative port which only serves that host name and matching certificate.

You seem to be using Apache, here's more info on this subject for that server:

https://wiki.apache.org/httpd/NameBasedSSLVHostsWithSNI
