### ISSUE TITLE
Empty feed

### ISSUE THREAD

**Issue by ximen** [Yetangitu/owncloud-apps#6]
Hello.

I have just installed files_opds in OC8 and uploaded my Calibre library, but it shows me empty feed (tested in Android FBReader and Chromium browser). oc_opds_metadata in sqlite database also seems empty. No errors or any other related messages in logs. It looks like library scan was not performed at all.

Thank you.

**Comment by Yetangitu** [comment]
sqlite.. I did not test with that database. This could be the cause.

Try the version I just committed, if it still does not work I'll have to do some testing with sqlite - which means I'll have to setup a test environment with that DB.

The 'library scan' is not performed up-front, it happens when you visit directories with publications in them. Make sure OPDS catalog is configured correctly, the library directory should be visible from within the file browser in OC.

**Comment by Yetangitu** [comment]
I just tested OPDS catalog in a new OC8 instance with sqlite. It seems to work as intended. Please check your configuration, especially the OPDS catalog root directory.

I did notice OC8 complains about sqlite 'not being supported' due to the fact that I used 'sqlite3' in the app info.xml file. This will be changed in the next release - soon - but it does not seem to cause any problems.

**Comment by ximen** [comment]
Thank you! Now it works fine. It was really my mistake: clearing "Supported extensions" field resolved this issue. Somehow "pdf,fb2" in this field was creating subject problem. Thank you once again.
